sequenceDiagram
    actor User

    %% User Activates a Control
    User->>+UIControl: Activates

    %% Control fires an action level event
    create participant ActionEvent
    UIControl->>ActionEvent: Create
    UIControl->>+PubSubManager: Fire Event
    
    %% Mediator recieves the event
    PubSubManager--)+OrgPageMediator: Sends Event 
    PubSubManager->>-UIControl: void   
    UIControl->>-User:void

    %% Org View Mediator updates the org structure, and fires org structure changed event
    OrgPageMediator->>+OrgStructure: Updates
    OrgStructure->>-OrgPageMediator: void
    create participant OrgStructureChangeEvent
    OrgPageMediator->>OrgStructureChangeEvent: Create
    OrgPageMediator->>+PubSubManager: Fire Event
    
    %% Any number of sub views handle the org structure changed event and updates
    PubSubManager--)+OrgPageSubview: Sends Event
    PubSubManager->>-OrgPageMediator: void
    
    OrgPageMediator->>-PubSubManager: void
    OrgPageSubview->>OrgPageSubview: Process and Update
    OrgPageSubview->>-PubSubManager: void

        

    
    

   