sequenceDiagram
    actor User

    %% User Activates a Control
    User->>+NewEmployeeToolbarButtonListener: Activates
    

    %% Toolbar fires an AddEmployeeToolbarEvent event
    create participant AddEmployeeToolbarEvent
    NewEmployeeToolbarButtonListener->>AddEmployeeToolbarEvent: Create
    NewEmployeeToolbarButtonListener->>+PubSubManager: Fire AddEmployeeToolbarEvent Event
    
    %% Mediator recieves the event
    PubSubManager--)+OrgPageMediatorSvelte: Sends AddEmployeeToolbarEvent Event 
    PubSubManager->>-NewEmployeeToolbarButtonListener: void   
    NewEmployeeToolbarButtonListener->>-User:void

    %% Org View Mediator Svelte Component Opens Modal
    OrgPageMediatorSvelte->>+OrgPageMediator: getSelectedManager()
    OrgPageMediator->>-OrgPageMediatorSvelte: Selected Manager
    OrgPageMediatorSvelte->>+ShowAddEmployeeModal: Open with Selected Manager
    OrgPageMediatorSvelte->>-PubSubManager: void

    %% User Submit Model
    User->>+ShowAddEmployeeModal:Submit
    create participant NewEmployeeEvent
    ShowAddEmployeeModal->>+NewEmployeeEvent: Create

    ShowAddEmployeeModal->>+PubSubManager: Fire NewEmployeeEven Event
    PubSubManager--)+OrgPageMediator: Sends NewEmployeeEven Event
    PubSubManager->>-ShowAddEmployeeModal: void
    ShowAddEmployeeModal-->-User:void

    %% Org View Mediator updates the org structure, and fires org structure changed event
    OrgPageMediator->>+OrgStructure: Updates
    OrgStructure->>-OrgPageMediator: void
    create participant OrgStructureChangeEvent
    OrgPageMediator->>OrgStructureChangeEvent: Create
    OrgPageMediator->>+PubSubManager: Fire Event
    
    %% Any number of sub views handle the org structure changed event and updates
    PubSubManager--)+OrgChartProxy: Sends Event
    PubSubManager->>-OrgPageMediator: void
    
    OrgPageMediator->>-PubSubManager: void
    OrgChartProxy->>OrgChartProxy: Process and Update
    OrgChartProxy->>-PubSubManager: void

        

    
    